# Generated by Django 5.2.5 on 2025-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('banner_type', models.CharField(choices=[('featured', 'Featured Banner'), ('simple', 'Simple Banner'), ('vendor', 'Vendor Banner')], default='simple', max_length=20)),
                ('button_text', models.CharField(default='XARID QILISH', max_length=50)),
                ('button_url', models.URLField(default='/shop')),
                ('background_color', models.CharField(default='#3B82F6', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('icon', models.CharField(default='Store', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
