# Generated by Django 5.2.5 on 2025-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
