# Generated by Django 5.2.5 on 2025-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_banner_image_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(default='/shop', max_length=200),
        ),
    ]
