# Generated by Django 5.2.5 on 2025-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_banner_button_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
