# Generated by Django 5.2.5 on 2025-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booked_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Зарезервированное количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Комиссия за реферальную продажу', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='referral_enabled',
            field=models.BooleanField(default=True, help_text='Включена ли реферальная система для этого товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент продаж', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='total_referral_sales',
            field=models.PositiveIntegerField(default=0, help_text='Количество продаж по реферальным ссылкам'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество продаж'),
        ),
    ]
