# Generated by Django 5.2.5 on 2025-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralvisit',
            name='page_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
