# Generated by Django 5.2.5 on 2025-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_referralvisit_page_url_referralvisit_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
